### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ghecko** [He-No/ntlmrelayx2proxychains#2]
When the tools is running to list available shares and no output file is specified, a traceback is returned at the end of the execution (line 222: with open...)
Error:
FileNotFoundError: [No such file or directory]

**Comment by He-No** [comment]
While running the tool, are you sure there was valid output to be written to the file? An issue that I'm aware of at the moment is that when no output is generated by the tool, this functionality indeed dares to provide a FileNotFoundError. A temporary workaround is to create a file with the exact file name in advance. Will try to look into this issue asap for a proper fix! (time constraint)

**Comment by He-No** [comment]
Added an error handler (except OSError as e) for this issue. Output "No ouptut to clean" will now be provided when the file does not exist (yet). Can you verify the resolution of this issue from your side?

Thanks again for your feedback!

**Comment by He-No** [comment]
Have you gotten a chance to (re)test this issue after I made some changes? As I'm under the impression that I resolved this issue, I'll close this tomorrow around 6 pm CET time if no additional information is provided.
